spring:
  profiles:
    active: local

---

spring:
  profiles: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true

logging:
  level:
    root: warn
    me.mirotic.demo: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
